// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go-zero-trace-demo/internal/logic"
	"go-zero-trace-demo/internal/svc"
	"go-zero-trace-demo/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) RandSentence(ctx context.Context, in *pb.RandSentenceReq) (*pb.RandSentenceResp, error) {
	l := logic.NewRandSentenceLogic(ctx, s.svcCtx)
	return l.RandSentence(in)
}

func (s *UserServer) RandError(ctx context.Context, in *pb.RandErrorReq) (*pb.RandErrorResp, error) {
	l := logic.NewRandErrorLogic(ctx, s.svcCtx)
	return l.RandError(in)
}
